apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goat-api-ingress  
spec:
  rules:
    - host: goat.apis.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goat-api-svc
                port:
                  number: 80
