apiVersion: v1
kind: Service
metadata:
  labels:
    app: tour-of-heroes-api
  name: tour-of-heroes-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    external-dns.alpha.kubernetes.io/hostname: tour-of-heroes.apis.internal
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 5000
  selector:
    app: tour-of-heroes-api
